### ISSUE TITLE
Make `FuzzUtilLimit` return random pieces of input set

### ISSUE THREAD

**Issue by MarvinJWendt** [MarvinJWendt/testza#154]
Make `FuzzUtilLimit` return random pieces of input set.

**Comment by KarolosLykos** [comment]
Hi @MarvinJWendt I was thinking of trying this one what do you think of something like that.

`func FuzzUtilLimit[setType any](testSet []setType, limit int) []setType {
	seen := map[int]bool{}

	if len(testSet) <= limit {
		return testSet
	}

	if limit <= 0 {
		return []setType{}
	}

	var result []setType

	counter := 0

	for counter < limit {
		index := rand.Intn(len(testSet) - 1)
		if !seen[index] {
			seen[index] = true
			result = append(result, testSet[index])
			counter++
		}

	}

	return result
}`

**Comment by MarvinJWendt** [comment]
Hi @KarolosLykos, this would definitely work, but I am not sure if the performance might be better with `rand.Shuffle`. We could then return a sub-slice of the shuffled slice (`shuffledTestSet[:limit]`). If you want to benchmark both approaches, feel free to do so, otherwise I'll do it in the next weeks and get back to you with the result :)

**Comment by KarolosLykos** [comment]
Hey @MarvinJWendt , I ran some benchmarks and `rand.Shuffle` is faster. Look at the benchmark tests and tell me what you think? `https://gist.github.com/KarolosLykos/c875274150bfdd9d11430fe2469a72a4`.

I also included a PR with the proposal.

**Comment by MarvinJWendt** [comment]
Fixed in #200 and released with `v0.5.2`. Thanks!
