### ISSUE TITLE
Startup message cannot be disabled

### ISSUE THREAD

**Issue by mikelorant** [MarvinJWendt/testza#164]
Due to the ordering of how `init()` is loaded from imports first, there is no way to actually set the startup message to be disabled within tests.

Looking at the unit tests, it is clear that only the variable is being checked, not that the output is being verified as not displayed which explains why it passes testing but does not actually do anything at all.

**Comment by MarvinJWendt** [comment]
Hi @mikelorant, sorry for the late response! The fix will be deployed in the next minutes. 🚀
