### ISSUE TITLE
Add mock time.Now()

### ISSUE THREAD

**Issue by Saltperfect** [MarvinJWendt/testza#2]
I have see a case where I had to test time.Now(), it could be done here.

**Comment by MarvinJWendt** [comment]
Hi @Saltperfect, could you please describe the feature a little more? What's the benefit of mocking time.Now(), over using time.Now() directly?
A little example would be great! :)

**Comment by Saltperfect** [comment]
@MarvinJWendt
 https://stackoverflow.com/questions/18970265/is-there-an-easy-way-to-stub-out-time-now-globally-during-test

I am talking about this.

**Comment by Saltperfect** [comment]
Can I raise a pr for this?

**Comment by MarvinJWendt** [comment]
Sure!

**Comment by MarvinJWendt** [comment]
Are you working on a PR @Saltperfect?
