### ISSUE TITLE
AssertNil doesn't work on non basic types

### ISSUE THREAD

**Issue by VasiliyS** [MarvinJWendt/testza#20]
pointers, etc will not work properly with `AssertNil` . The assert will fail for `nil` values and print:

```
1| An object that should be nil is not nil.
2| 
3| Expected:
4| (interface {}) <nil>
5| 
6| Actual:
7| (*main.record)(<nil>)
```

Here's a [GoPlay](https://play.golang.org/p/eo0-E5xq2IB) that illustrates it.

The solution would be to use reflect package and check for `nil` using `reflect.ValueOf(v).IsNil()` method.

Since I was surprised myself, I have found this [article](https://www.calhoun.io/when-nil-isnt-equal-to-nil/) that does a good job, IMHO, to explain why.

**Comment by MarvinJWendt** [comment]
This is now fixed in [`v0.2.5`](https://github.com/MarvinJWendt/testza/releases/tag/v0.2.5).
Thanks for reporting!
