### ISSUE TITLE
Change MockInput to Fuzz or Fuzzy

### ISSUE THREAD

**Issue by MarvinJWendt** [MarvinJWendt/testza#64]
Changing `MockInput` to Fuzz or Fuzzy would make the name fit better, as fuzzy testing describes using random input values for unit tests.

**Comment by KarolosLykos** [comment]
Hi @MarvinJWendt , I would like to take this one. Is this just changing the name everywhere and refactor the code to use the new one?

**Comment by MarvinJWendt** [comment]
Hi @KarolosLykos, I am currently unsure if we really need this, as fuzz testing will be included in the stdlib starting with Go 1.18. I am thinking about removing the Fuzz feature then. I'll let you know when I came to a conclusion!
