### ISSUE TITLE
Rich git-like string diff

### ISSUE THREAD

**Issue by Vilsol** [MarvinJWendt/testza#96]
Currently if you are comparing strings with testza, it only detects if they are different, but not what is different within them as it does with structs. When comparing multiline strings, it gets even more confusing as finding the issue on large strings requires using external tools. 

Here's an example of current behavior: 
<img width="1526" alt="image" src="https://user-images.githubusercontent.com/1759390/160275288-f7458448-551a-4bb2-a2e1-d222907b5846.png">

It would be great if it was possible to have a rich git-like diff on a string. There are even libraries that have specialized for this within Go: https://github.com/sergi/go-diff

If this is a feature that would be accepted by the maintainers, I would be willing to implement it via PR.

**Comment by MarvinJWendt** [comment]
Hi @Vilsol, that would definitely make sense!

**Comment by Vilsol** [comment]
I am drawing up how to implement this in `testza` and it seems to be extremely simple, however I noticed a potential issue.

Looking at the library that is currently used for diffing objects (https://github.com/pmezard/go-difflib), it outputs a primitive git-compatible diff, which then is then post-processed by testza for terminal coloring.

I am wondering whether you would accept switching to the library I mentioned in the initial issue (https://github.com/sergi/go-diff) as that would give us much more modern and rich diff results, and remove the need for any kind of string post-processing (as that library returns an array object of changes). With that we could achieve github-like git diffs e.g.

<img width="397" alt="image" src="https://user-images.githubusercontent.com/1759390/160295717-bebbf332-6d42-40b5-b162-0e9a446b23d1.png">
<img width="259" alt="image" src="https://user-images.githubusercontent.com/1759390/160295725-dbc023e6-e7eb-428f-846e-2398f453d0a3.png">

It also seems like the `go-difflib` has been archived and unmaintained since 2018.

**Comment by MarvinJWendt** [comment]
Yes, I'd be fine with that, but we have to keep [go-difflib](https://github.com/pmezard/go-difflib) for snapshots, as they would most likely break in every project that is using `testza`, when we switch the library. For the visual output, we can change to your suggestion!

> [...] and remove the need for any kind of string post-processing (as that library returns an array object of changes).

We'd still have to add the colors ourselves, right? 

You can create a draft PR when you start :)
